### ISSUE TITLE
Introduction to `ember-pouch` at Global Ember Meetup

### ISSUE THREAD

**Issue by taras** [nolanlawson/ember-pouch#114]
@nolanlawson will be giving a talk on Web Workers on April 9th at Global Ember Meetup. Would you like to make it a double feature with an `Introduction to ember-pouch` talk?

`Introduction to` talks answer the following 3 questions:
1. Why was this addon created? (what use case is it trying to address)
2. How do you use it?
3. What should the user be aware of?

After the talk, we'll edit the video and submit a PR with a link to the videos in the README. You can see some other `Introduction to` talks here https://vimeo.com/album/3607049

What do you think?

**Comment by nolanlawson** [comment]
Hey, thanks for the shout-out! :) Funnily enough, I think by this point I wouldn't be qualified to talk much about ember-pouch, because the truth is that it is mostly community-maintained right now, and I am pretty weak on the Ember specifics of the project. I wrote it over the span of a few weekends for a very old version of Ember Data, and it's changed significantly since then.

Regardless, I'd be happy to talk a bit about ember-pouch if anyone's interested, though. :) I can at least talk about the genesis of the project, and how amazing I discovered the Ember community to be!

**Comment by taras** [comment]
I was going to suggest that someone else who's familiar with the project does this introduction :)

**Comment by pjcarly** [comment]
An introduction talk would be aces! I can't wait until I can work with this add-on and would be very interested to attend an introduction talk.

**Comment by taras** [comment]
Oh, I can see why @nolanlawson you thought I was asking you to give 2 talks - it's how I wrote my request :) Sorry, I meant, making it a double feature by having someone from this project give the talk. Not necessarily @nolanlawson, but you're such a great sport. Thank you :)

**Comment by nolanlawson** [comment]
Ah okay, gotcha! :) Yes, someone from this project (not me!) should give the talk, for sure.

**Comment by gr2m** [comment]
I think this issue can be closed? (sorry for the noise, I’m going trough the issues to find known issues and thought I’d ping you to help close the ones that are no longer relevant)
