### ISSUE TITLE
destroyDB() + ember-data-factory-guy + findAll = error

### ISSUE THREAD

**Issue by Fed03** [nolanlawson/ember-pouch#125]
Hi all,
I've the following acceptance test file 
https://github.com/Fed03/pie/blob/acceptancePouch/tests/acceptance/show-current-month-test.js

that's working perfectly. If I install `ember-data-factory-guy`, the test throws this error
`invalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.`

I should point that visiting / , calls findAll then redirect accordingly.
Naturally if you delete the  `ember-data-factory-guy` line from `package.json` all return green.

I already spoke with the creator of `ember-data-factory-guy`, @danielspaniel,but we cannot find the error.
However I can explain you what `ember-data-factory-guy` does when `startApp` is called:

1. this function is called    
https://github.com/danielspaniel/ember-data-factory-guy/blob/v2.4.4/addon/utils/manual-setup.js
2. [`FactoryGuy.setStore()`](https://github.com/danielspaniel/ember-data-factory-guy/blob/v2.4.4/addon/factory-guy.js#L65-L70) calls the [`FixtureBuilderFactory` constructor](https://github.com/danielspaniel/ember-data-factory-guy/blob/v2.4.4/addon/builder/fixture-builder-factory.js#L7-L10)
3. inside it, `store.adapterFor('application')` is called and I believe the problem lays here

If some of you could help me to investigate and resolve this sorcery, I'll gladly send a beer all over the world XD

P.s. the repository I linked at the beginning is ready to be cloned and tested: the branch is `acceptancePouch` and it comes without `ember-data-factory-guy` so the test is green

**Comment by nolanlawson** [comment]
Typically the reason this happens is because there is a concurrent IDB operation while you're destroying. I.e. you're doing `destroy()` at the same time that you're doing `get()` or `allDocs()` or something else.

This gets trickier when you're using map/reduce. Basically in that case you need to make sure that all of your `query()`s have completed before you call `destroy()`. If you turn on PouchDB's [debug logging](https://pouchdb.com/api.html#debug_mode), it may help elucidate.
