### ISSUE TITLE
Saving attachment data & retrieving.

### ISSUE THREAD

**Issue by hashg** [nolanlawson/ember-pouch#169]
I'm trying to attach and retrieve the data back using ember-pouch "attachment". But after saving the data, there are issues reading the attachment data which is returned as "undefined".

![empouch](https://cloud.githubusercontent.com/assets/309076/22361878/ea77799a-e412-11e6-9c7f-0c238238b4be.png)

## Repo
> Issue is reproducing using my repo - [empouch-attach](https://github.com/hashg/empouch-attach)

### Currently my repo implements :
1. Save model `without any` attachments
2. Add `single file` to attachment

## Code
Using [ember-cli-file-picker](https://github.com/funkensturm/ember-cli-file-picker) addon to "Upload files"

### .hbs
```hbs
{{#file-picker fileLoaded="photoAdded" readAs="readAsFile" accept="image/*"}}
  <button type="button" name="button">Click to upload a photo</button>
{{/file-picker}}
```

### route/actions

```js
    photoAdded(file) {
      const profile = this.controller.get('model');
      const selections = Ember.get(profile, 'photo');
      Ember.Logger.debug(file);

      selections.addObject(Ember.Object.create({
        'name' : file.name,
        'content_type' : file.type,
        'data' : file
      }));
      Ember.Logger.debug(profile);
      profile.save();
   }

```

### Scenarios I'm trying to understand :

1. Save model `without any` attachments
2. Add `single file` to attachment
3. Add `mutiple files` to attachment
4. Edit model & `add more files` to attachment
5. `Remove file/s` from attachment
6. `Retrieve file/s` from attachment

I'm stuck @  `Retrieve file/s` from attachment. I've a doubt my save mechanism scrambles the model data.

[Edit: More info + format]

**Comment by srsgores** [comment]
Hi @hashg.

I have gotten attachments to work.  It turns out there is a typo in the readme.  In order to get attachments working properly, **you have to rename your ``DS.attr("attachment"`` to ``DS.attr("attachment__s__"``**.  When using the former, you will see that ``defaultValue`` has no effect; but if you use the latter, the ``defaultValue`` **will** work:

```
import Model from "ember-pouch/model";
const {attr, hasMany, belongsTo} = DS;

export default Model.extend({
    photos: attr("attachments", {defaultValue: []}), // note the "s" here
    // ...
});
```

To add attachments, the process **is** as described in the readme (just note the "s" in the ``DS.attr`` call).  You can call ``model.get("photos").addObject();``.  Of note, however: I was not able to save ``File``s directly in the ``data`` field; I had to base64-encode the data.

Now, to answer your question regarding the displaying and retrieving said attachments: you can accomplish this with an ``{{each}}`` statement:

```
<figure class="images-container">
	{{#each model.photos as |photo|}}
		<img src="{{photo.data}}" alt="{model.post.name}}">
	{{/each}}
	<figcaption class="post-image-description">
		{{model.food.name}}
	</figcaption>
</figure>
```

Of note, this works because a [base64-encoded string is a valid value for ``src``](http://www.hongkiat.com/blog/css-encoded-image/).

I hope that helps!

**Comment by broerse** [comment]
@srsgores Super! Can you make a PR for the readme? I will merge it.

**Comment by ntodd** [comment]
@broerse I updated the readme in https://github.com/nolanlawson/ember-pouch/pull/170

**Comment by broerse** [comment]
@ntodd Thanks
