### ISSUE TITLE
Increment ember-pouch version

### ISSUE THREAD

**Issue by OleRoel** [nolanlawson/ember-pouch#76]
Can we do a minor version increment to reflect the code changes with the last two or so PRs? When I do a `npm install ember-pouch` or `ember install ember-pouch` I still get an old version of ember-pouch which is not identical to the GitHub repo. I guess npm caches the code and doesn't update it until the version number has been incremented. At least their website says "nolanlawson published 3 weeks ago": https://www.npmjs.com/package/ember-pouch

**Comment by rsutphin** [comment]
Incrementing the version doesn't automatically make the new version available on NPM. There's an explicit publishing step that the package owner does. @nolanlawson generally does this pretty regularly — I'm sure he'll do it as soon as he's had a chance to review the recent changes.

In the meantime, you can point your package.json at this git repo to get a version with the latest changes. I recommend locking to a specific rev so that you have reproducible builds, though you can also just a branch name if you like living dangerously.

```
    "ember-pouch": "git://github.com/nolanlawson/ember-pouch#44b2019eea"
```

**Comment by OleRoel** [comment]
@rsutphin Yep, this is what I did in the package.json. But only after I stumbeld upon the fact that ED 13.4 build throws exceptions with the regular npm install in my project. Pushing a new version to npm will avoid disapointed users that are using the latest ED.

**Comment by rsutphin** [comment]
2.0.2 is published.

**Comment by broerse** [comment]
Thanks for your work on ember-pouch. It would be a great setting on github to set releases tag's to follow the package.json automatically. But it is not an option yet ;-( 

You must set the release to 2.0.2 by hand for it is now still on 2.0.1

**Comment by rsutphin** [comment]
Oops, forgot to push the tag, which is what GitHub's "releases" is based on. Should be good now.
